add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$character"""

[username]
style_root = "bold green"
style_user = "bold green"
show_always = false

[hostname] 
ssh_only = false
format = '[$hostname]($style) in '
trim_at = "."
style = "bold green"
disabled = true

[directory]
truncation_length = 999
truncate_to_repo = true
truncation_symbol = ""
style = "bold blue"

[git_branch]
style = "bold purple"

[git_state]
cherry_pick = "CHERRY PICKING"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "bold purple"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'bold purple'
stashed = '\$'
ahead = '⇡'
behind = '⇣'
up_to_date = ''
diverged = '⇕'
conflicted = '!'
deleted = 'D'
renamed = 'R'
modified = 'M'
staged = '+'
untracked = '?'

[character]
format = '$symbol '
success_symbol = '❯'
error_symbol = '❯'
vicmd_symbol = '❮'
disabled = true

