include:
  - path: Layouts/*
    destination: Layouts
  - path: ScriptTemplates/*

windows:
  destination: "%programfiles%/Unity/Hub/Editor/*/Editor/Data/Resources"
macos:
  destination: "/Applications/Unity/Hub/Editor/*/Unity.app/Contents/Resources"
