include:
  - path: vlcrc
  - path: vlc-qt-interface.ini
windows:
  destination: '%appdata%/vlc'
macos:
  destination: ~/Library/Preferences/org.videolan.vlc
linux:
  destination: ~/.config/vlc
