include:
  - path: settings.json
    destination: LocalState/
  - path: backgrounds/yokohama.png
  - path: backgrounds/kicho.png
windows:
  destination: '%localappdata%/Packages/Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe'
