#!/usr/bin/env bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

branch=$(git branch --show-current)
if echo $branch | grep -q '^feature/'
then
	name=${branch#feature/}
	if echo $name | grep -q '^[[:digit:]]*$'
	then
		message="\n\nImplementing #$name"
	else
		message="\n\nImplementing feature \"$name\""
	fi
else
	message=""
fi

sed -i.bak "/# Please enter.*ending of the thing\./ s///" $COMMIT_MSG_FILE
sed -i.bak "/#%{git_feature}/ s//$message/" $COMMIT_MSG_FILE
