#!/usr/bin/env bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# Remove default commit string
/usr/bin/perl -i.bak -ne 'print unless(m/^. Please enter the commit message/..m/^#$/)' "$COMMIT_MSG_FILE"

# Replace issue/feature string
branch=$(git branch --show-current)
if echo $branch | grep -q '^feature-'
then
	name=${branch#feature-}
	if echo $name | grep -q '^[[:digit:]]*$'
	then
		message="\n\nImplementing #$name"
	else
		message="\n\nImplementing feature \"$name\""
	fi
else
	message=""
fi
sed -i.bak "/#%{git_feature}/ s//$message/" $COMMIT_MSG_FILE
