[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
no-ligation = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss16"
