include:
  - path: CurrentSettings.vssettings
    symlink: true
  - path: snippets
    destination: "%userprofile%/Documents/Visual Studio */Code Snippets/Visual C#/My Code Snippets"
    symlink: true

windows:
  destination: "%localappdata%/Microsoft/VisualStudio/17.*/Settings"
