#!/usr/bin/env bash

branch=$(git branch --show-current)
if echo $branch | grep -q '^feature/'
then
	name=${branch#feature/}
	if echo $name | grep -q '^[[:digit:]]*$'
	then
		message="\n\nImplementing #$name"
	else
		message="\n\nImplementing feature \"$name\""
	fi
else
	message=""
fi

sed -i.bak "/#%{git_feature}/ s//$message/" $1
