include:
  - path: settings.json
  - path: Keyboard Manager/default.json
  - path: Keyboard Manager/settings.json
  - path: PowerToys Run/settings.json

windows:
  destination: "%localappdata%/Microsoft/PowerToys"
