include:
  - path: settings.json
  - path: keybindings.json
  - path: snippets
windows:
  destination: '%appdata%/Code/User'
macos:
  destination: ~/Library/Application Support/Code User/settings.json
linux:
  destination: ~/.config/Code/User
