. ~/dotfiles/shell/ls_colors

# Aliases
alias g=git
alias ls=eza
alias m=micro

# Configure zoxide
eval "$(starship init zsh)"

# Configure starship
eval "$(zoxide init zsh)"
export _ZO_ECHO=1
export _ZO_RESOLVE_SYMLINKS=1
