#!/usr/bin/env bash

filename=$(realpath "$1")
GREEN='\033[0;32m'
NC='\033[0m'

echo "Creating $filename"
$( var='#!/usr/bin/env bash\n\necho "Hello World!"'; printf '%b\n' "$var" > "$filename" )
chmod +x "$filename"

echo -e "$GREEN... '$filename' [Created]$NC"
